// UI copy lives outside simulation/rendering so another locale can provide the same keys.
export const en = {
  brand: "LAST LIGHT",
  tagline: "MAKE THE MOMENT.",
  play: "Play career",
  continue: "Continue career",
  career: "The journey",
  daily: "Daily shot",
  customize: "Your player",
  stats: "Your record",
  settings: "Settings",
  home: "Back to home",
  retry: "Try again",
  next: "Next moment",
  replay: "Watch replay",
  share: "Challenge a friend",
  resume: "Back to the match",
  pause: "Match paused",
  draw: "Draw from the ball. Make your move.",
  first: "Draw from the ball to your teammate.",
  shoot: "Pick your corner. Draw toward the goal.",
  lift: "Lifted",
  driven: "Driven",
  saved: "Progress saved on this device",
  goal: "GOAL",
  failure: "ANOTHER CHANCE.",
  results: "MOMENT COMPLETE",
};
